apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/janmoeller2023/gitops-workshop.git
    targetRevision: main
    path: apps/overlays/dev # Points to the Dev settings
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-dev # Deploys to the Dev namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

